# NumPy Practice Exercises

Complete the following exercises to practice NumPy operations. Write your code in the empty code cells below each instruction.

### 1. Basic Array Creation
- Import NumPy as np
- Create a 1D array [1,2,3] and set its type to 'int32'
- Create a 2D array [[9.0,8.0,7.0],[6.0,5.0,4.0]]

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3], dtype='int32')
print(arr)

[1 2 3]


In [3]:
arr=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(arr)

[[9. 8. 7.]
 [6. 5. 4.]]


### 2. Array Information
For each array created above:
- Get the dimension (ndim)
- Get the shape
- Get the data type
- Get the size (number of elements)
- Get the itemsize (size in bytes of each element)
- Get the total size in bytes (nbytes)

In [4]:
arr.ndim

2

In [5]:
arr.shape

(2, 3)

In [6]:
arr.dtype

dtype('float64')

In [7]:
arr.size

6

In [8]:
arr.itemsize

8

In [9]:
arr.nbytes

48

### 3. Array Indexing and Slicing
Create this 2D array: [[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]] and then:
- Get element at position [1,5] (row 1, column 5)
- Get entire first row
- Get entire third column
- Get elements from first row with step size 2
- Change value at [1,5] to 20
- Change entire third column to [1,2]

In [11]:
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

print(arr[1,5])

print(arr[0,:])

print(arr[:,2])

print(arr[0,::2])

arr[1,5]=20
print(arr)

arr[:,2]=[1,2]
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[1 3 5 7]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 4. Array Initialization
Create the following arrays:
- A 2x3 array of zeros
- A 4x2x2 array of ones with type 'int32'
- A 2x2 array filled with the number 99
- A 4x2 array of random decimal numbers between 0 and 1
- A 3x3 array of random integers between -4 and 8
- A 5x5 identity matrix

In [ ]:
zero-array=np.zeros((2,3))
print(zero-array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
onesArray=np.ones((4,2,2), dtype='int32')
print(onesArray)

ninetyNineArray=np.full((2,2), 99)
print(ninetyNineArray)

randomArray=np.random.rand(4,2)*100
print(randomArray)

randomIntArray=np.random.randint(-4,8, size=(3,3))
print(randomIntArray)

identityMatrix=np.eye(5)
print(identityMatrix)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99 99]
 [99 99]]
[[54.59669764 71.97703122]
 [88.25069989 32.71585056]
 [27.47267744 93.72500673]
 [38.11548832 29.3882735 ]]
[[-3  1  5]
 [-2 -2  1]
 [ 4 -4  0]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5. Array Mathematics
Create array [1,2,3,4] and perform:
- Add 2 to each element
- Subtract 2 from each element
- Multiply each element by 2
- Divide each element by 2
- Calculate square of each element
- Calculate sine of each element
- Add two arrays element-wise

In [19]:
arr=np.array([1,2,3,4])
print(arr)

print(arr+2)

print(arr-2)

print(arr*2)

print(arr/2)

print(np.square(arr))

print(np.sin(arr))

arr2=np.array([5,6,7,8])
print(arr2)

print(arr+arr2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[5 6 7 8]
[ 6  8 10 12]


### 6. Linear Algebra
- Create a 2x3 array of ones
- Create a 3x2 array filled with 2's
- Perform matrix multiplication of these arrays
- Create a 3x3 identity matrix and find its determinant

In [20]:
larr=np.ones((2,3))
print(larr)

larr2=np.full((3,2), 2)
print(larr2)

print(np.matmul(larr,larr2))

identityMatrix=np.eye(3)
print(identityMatrix)

print(np.linalg.det(identityMatrix))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


### 7. Statistics
Create array [[1,2,3],[4,5,6]] and find:
- Minimum value
- Maximum value of each row
- Sum of each column

In [23]:
num=np.array([[1,2,3],[4,5,6]])
print(num)

print(np.min(num))

print(np.max(num, axis=1))

print(np.sum(num, axis=0))

[[1 2 3]
 [4 5 6]]
1
[3 6]
[5 7 9]


### 8. Array Manipulation
- Create two vectors [1,2,3,4] and [5,6,7,8]
- Stack them vertically
- Create a 2x4 array of ones and a 2x2 array of zeros
- Stack them horizontally

In [24]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1)
print(arr2)

print(np.vstack((arr1,arr2)))

arr3=np.ones((2,4))
arr4=np.zeros((2,2))
print(arr3)
print(arr4)

print(np.hstack((arr3,arr4)))

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


### 9. Advanced Exercise: Create a Pattern
Create this pattern using NumPy arrays:
```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```
Hint: Use ones, zeros, and array indexing

In [26]:
ones=np.ones((5,5))
zeroes=np.zeros((3,3))
ones[1:4,1:4]=zeroes
ones[2,2]=9
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
